### PR TITLE
Profiling and Profile Optimised Builds

### PR DESCRIPTION
**Pull request by Miouyouyou**
I added a **Profile Guided Optimisations** build target to your project, which should help you : 
- profile the performance of your application, using tools like gcovr or lcov ;
- generate binaries that are optimised based on these profiling informations.

The main use is simple.

```
$ make distclean
$ make pgo-firstpass
# Use your software like you're used to, on the build machine.
# This should generate .gcda and .gcno files. These can then be analysed with
# gcov and similar tools.
$ make clean
$ make pgo-secondpass
# At this point, an optimised binary has been generated
```

Lcov : http://ltp.sourceforge.net/coverage/lcov.php
Gcovr: http://gcovr.com/guide.html
Eclipse plugin: https://wiki.eclipse.org/Linux_Tools_Project/GCov/User_Guide

### CODE REVIEW

**Comment by Miouyouyou** [comment]
More informations provided in your thread: https://community.arm.com/message/38759

**Comment by carlosdelfino** [comment]
Thanks.
In this week I make new tests.

**Comment by carlosdelfino** [comment]
I believe the target "clean" should be placed as dependent target "pgo-secondpass" thus preventing always have to be entered.
I will do this, since forgets it brings problems.

**Comment by Miouyouyou** [comment]
Oh yes, indeed !
Once you get a nice report from gprof, you might want to paste it in the Wiki.
Something like "TODO: Optimize these parts" might help other contributors to understand which parts they need to focus on.

**Comment by carlosdelfino** [comment]
E put report file in this path: https://github.com/carlosdelfino/ContadorDeCiclistas/tree/NanoPI-M3/profiling I think mark every commit with a tag and use them at issue.

About profiling I think the greate work is on OpenCV, because the code in question is very simple and demands little processing.

But when mSQL demand for recognition of the object type there may be an increased demand for analysis by both the best algortimo the openCV as improvements in the collection of images for training.

**Pull request merged**
